[package]
name = "magma_samples"
version = "0.1.1"
edition = "2021"

[dependencies]
cipher_magma = { path = "../cipher_magma" }
image = "0.24"
rayon = "1.7"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "magma_benchmark"
harness = false

